---
kind: pipeline
type: exec
name: silent-shard-exec-runner

platform:
  os: linux
  arch: amd64

steps:
- name: build apk
  environment:
    MIX_PANEL_TOKEN:
      from_secret: MIX_PANEL_TOKEN
    STOREPASSWORD:
      from_secret: STOREPASSWORD
    KEYPASSWORD:
      from_secret: KEYPASSWORD
    KEYALIAS:
      from_secret: KEYALIAS
    STOREFILE:
      from_secret: STOREFILE
    FIREBASE_TOKEN:
      from_secret: FIREBASE_TOKEN
  commands:
    - export ANDROID_SDK_ROOT="/opt/Android/"
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - echo $MIX_PANEL_TOKEN > .env
    - echo $STOREPASSWORD >> android/key.properties
    - echo $KEYPASSWORD >> android/key.properties
    - echo $KEYALIAS >> android/key.properties
    - echo $STOREFILE >> android/key.properties
    - dart pub global activate flutterfire_cli
    - flutterfire configure -y -p mobile-wallet-mm-snap
    - flutter build apk --release
    - cp -r build/app/outputs/flutter-apk/app-release.apk /builds/