---
kind: pipeline
type: exec
name: silent-shard-exec-runner

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
  - echo test
  - touch find_me
  - echo $DRONE_RUNNER_NAME