---
kind: pipeline
type: exec
name: silent-shard-exec-runner

platform:
  os: linux
  arch: amd64

steps:
- name: build apk
  environment:
    MIX_PANEL_TOKEN:
      from_secret: MIX_PANEL_TOKEN
    KEY_PROPERTIES:
      from_secret: KEY_PROPERTIES
  commands:
    - echo $MIX_PANEL_TOKEN > .env
    - mv $KEY_PROPERTIES android/key.properties
    - flutter build apk --release
    - cp -r build/app/outputs/flutter-apk/app-release.apk /builds/
