name: silentshard
description: Demonstrates how to use the dart_2_party_ecdsa plugin.
publish_to: 'none'

version: 1.2.7+242

environment:
  sdk: ^3.11.0

flutter_icons:
  image_path: "assets/icon/silentShardLogo.png"
  android: true
  ios: true
  remove_alpha_ios: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  app_settings: ^7.0.0
  cloud_functions: ^6.0.6
  firebase_crashlytics: ^5.0.7
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  dart_2_party_ecdsa:
    # path: ../silent-shard-flutter-sdk
    git:
      url: git@github.com:silence-laboratories/silent-shard-flutter-sdk.git
      ref: main
  firebase_core: ^4.4.0
  flutter_dotenv: ^6.0.0
  credential_manager: 2.0.8
  device_info_plus: ^12.3.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  mixpanel_flutter: ^2.5.0
  flutter_secure_storage: ^10.0.0
  share_plus: ^12.0.1
  file_picker: ^10.3.10
  firebase_remote_config: ^6.1.4
  local_auth: ^3.0.0
  firebase_messaging: ^16.1.1
  path_provider: ^2.1.5
  gap: ^3.0.1
  lottie: ^3.3.2
  url_launcher: ^6.3.2
  mobile_scanner: ^7.2.0
  permission_handler: ^12.0.1
  slide_to_act: ^2.0.2
  scrollable_positioned_list: ^0.3.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/lottie/
    - assets/json/
    - .env

  fonts:
    - family: Epilogue
      fonts:
        - asset: fonts/Epilogue/Epilogue-Regular.ttf
          weight: 400
        - asset: fonts/Epilogue/Epilogue-Medium.ttf
          weight: 500
        - asset: fonts/Epilogue/Epilogue-Bold.ttf
          weight: 700
        - asset: fonts/Epilogue/Epilogue-Italic.ttf
          style: italic
        - asset: fonts/Epilogue/Epilogue-Thin.ttf
          weight: 100
        - asset: fonts/Epilogue/Epilogue-ExtraLight.ttf
          weight: 200