# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "CI/CD" ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    env: 
      MIX_PANEL_TOKEN: ${{ secrets.MIX_PANEL_TOKEN }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      KEY_PROP: ${{ secrets.KEY_PROPERTIES }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: main
        run: | 
          echo MIX_PANEL_TOKEN=$MIX_PANEL_TOKEN > .env
          echo  $KEY_PROP | base64  -d > ./android/key.properties
          echo "dart pub global activate flutterfire_cli"
          dart pub global activate flutterfire_cli
          echo "ruby.gem install xcodeproj"
          ruby.gem install xcodeproj
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          echo "flutterfire configure  -y  -p mobile-wallet-mm-snap"
          flutterfire configure  -y  -p mobile-wallet-mm-snap
          echo "flutter build apk --release"
          flutter build apk --release
          cp -r build/app/outputs/flutter-apk/app-release.apk /builds/